[package]
name = "raydium-client"
version = "0.1.0"
rust-version = "1.56"
edition = "2021"

[dependencies]
anchor-client = "0.29.0"
anchor-lang = "0.29.0"
raydium-amm-v3 = {path = "../programs/amm", features = ["no-entrypoint", "client"]}

solana-client = { path="/Users/jd/jito-solana/client" }
solana-metrics ={ path="/Users/jd/jito-solana/metrics" }
solana-sdk = { path="/Users/jd/jito-solana/sdk" }
solana-transaction-status = { path="/Users/jd/jito-solana/transaction-status" }
solana-account-decoder = { path = "/Users/jd/jito-solana/account-decoder" }
spl-token = { version = "4.0.0", features=["no-entrypoint"] }
spl-token-client = "^0.8.0"
spl-memo = "4.0.0"
spl-associated-token-account = { version = "2.3.0", features = ["no-entrypoint"]}
spl-token-2022 = { version = "0.9.0", features = ["no-entrypoint"]}
mpl-token-metadata = { version = "4.1.1" }
clap = { version = "4.1.8", features = ["derive"] }
anyhow = "1.0.32"
rand = "0.7.3"
hex = "0.4.3"
configparser = "3.0.0"
serde_json = { version = "1.0.78" }
serde = { version = "1.0", features = ["derive"] }
arrayref = "0.3.7"
bs58 = { version = "0.5.0"}
bincode = { version = "1.3.3" }
regex = "1"
colorful = "0.2.2"